# Generated by Django 5.1.14 on 2026-07-16 11:24

import bots.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0086_alter_bot_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=bots.storage.StorageAlias('audio_recordings'), upload_to=''),
        ),
    ]
